### ISSUE TITLE
RecursionError due to contract checking during contract checking

### ISSUE THREAD

**Issue by markusschmaus** [Parquery/icontract#126] opened 2020-04-14 09:40 UTC
```
from typing import Any

from icontract import DBC, ensure


class Dimension(DBC):
    @ensure(lambda self, label, result: self.label(result) == label)
    def index(self, label: Any) -> int:
        return int(label)

    @ensure(lambda self, index, result: self.index(result) == index)
    def label(self, index: int) -> Any:
        return str(index)


x = Dimension()
print(x.label(0))
```

This code results in a RecursionError, since while checking the postcondition for `label` the method `index` is invoked which triggers the check for the postcondition of `index`.

It would be great if it were possible to suspend the checking of any other contracts while checking one contract, either by default or as a option when specifying the contract.

**Comment by mristin** [comment] 2020-04-14 19:59
Hi @markusschmaus ,
Thanks for the feature request! I actually encountered the conundrum of recursive contract checking while designing the library. In the end, I thought it would be too surprising for the user if some contracts were not checked and decide to leave the issue aside.

What about a pattern where you do:
```python
def _some_function_nodbc(...):
    ...

@require ...
def some_function(...):
    return _some_function_nodbc(...)
```
and then you explicitly call the function without the contracts in other contracts?

However, this pattern would solve only your concrete problem. Actually, you might have the recursion much deeper in the nested calls when evaluating a contract so you would have to disable all contracts globally while evaluating a contract, wouldn't you? 

Let's brainstorm a bit together first. I feel that the issue is more complex then it appears.

**Comment by markusschmaus** [comment] 2020-04-15 09:19
I intend `Dimension` to be an abstract base class with sub-classes providing concrete implementations of `label` and `index`. The pattern you suggest would mean that the sub-classes would instead provide implementations for _`label_nodbc` and `_index_nodbc` which would also get the docstring, while only `index` and `label` should be used publicly. I must admit I am not super fond of that solution.

My first idea was to disable contract checking globally while evaluating a contract. I think it might be useful to have a `ContextDecorator` which allows the programmer to disable context checking in some circumstances, and then this could be used in the contract, either explicitly in the function as a `with` block or as a flag when specifying the contract.

Another option I thought about was to only disable checking the contracts for the same function, by setting a flag on the contract checker and skip checking the pre- and postconditions if that flag is currently set.

**Comment by mristin** [comment] 2020-04-15 18:32
Hi @markusschmaus ,
> Another option I thought about was to only disable checking the contracts for the same function, by setting a flag on the contract checker and skip checking the pre- and postconditions if that flag is currently set.

I like this solution the best. Let me think about how it can be implemented for a couple of days. Any suggestions are of course welcome!

**Comment by markusschmaus** [comment] 2020-04-16 08:48
This is what I was thinking about:
https://github.com/markusschmaus/icontract/commit/9c5884a1f848c7f3068528b34e8c56029569e502

**Comment by mristin** [comment] 2020-04-16 20:39
Hi @markusschmaus ,
I tried to implement your suggestion and write a couple of unit tests. I added the exit stack to make sure everything goes back to the initial state in case of exceptions, but the rest is merely a copy/paste.

The solution works well for preconditions and postconditions:
https://github.com/mristin/icontract/commit/5769153e3018f2c18e1b71a23af03d5c9e2b6641

However, I got stuck with the invariants. Please see the last test case in `test_recursion.py`. Would you mind having a look at how to solve the recursive invariants? Maybe you'll have an idea immediately. I tried naively to implement a fix with a counter, but that didn't solve it.

**Comment by mristin** [comment] 2020-04-17 10:35
@markusschmaus actually, as soon as the first invariant is checked, _all_ the invariants of the class need to be temporarily disabled to avoid endless recursion, needn't they?

**Comment by mristin** [comment] 2020-04-21 20:15
Hi @markusschmaus ,
I implemented the suggestion in the following pull request:  #129 

Would you mind to review it? Could you maybe come up with additional unit tests? (You can also just sketch them and I will implement them if that is easier for you.)

Once we merge this in and #128 , the patch version can be bumped and released.

**Comment by mristin** [comment] 2020-04-30 07:23
#129 fixes this issue. @Sasha93 we can close it.

**Comment by mristin** [comment] 2020-05-08 07:02
(@Sasha93 a kind reminder)

**Closed** 2020-05-11 07:02 UTC
