### ISSUE TITLE
Missing arg for ViolationError in python 3.10

### ISSUE THREAD

**Issue by claudio-ebel** [Parquery/icontract#235] opened 2021-11-22 20:20 UTC
Minimal working example in `/tmp/spam.py`:

```python
from icontract import require, ViolationError


@require(lambda _ARGS: bool([s for s in _ARGS]))
def spam(*args):
    pass


if __name__ == '__main__':
    try:
        spam(*[])
    except ViolationError:
        print(bool([s for s in []]))
```

Expected behavior (python `3.9`): 

```shell
$ python --version
Python 3.9.7
$ python -m pip freeze | grep icontract
icontract==2.5.5
$ python /tmp/spam.py
False
```

False behavior (python `3.10`):

```shell
$ python --version
Python 3.10.0
$ python -m pip freeze | grep icontract
icontract==2.5.5
$ python /tmp/spam.py
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.10/site-packages/icontract/_checkers.py", line 181, in _create_violation_error
    msg = icontract._represent.generate_message(contract=contract, resolved_kwargs=resolved_kwargs)
  File "/tmp/venv/lib/python3.10/site-packages/icontract/_represent.py", line 542, in generate_message
    repr_vals = repr_values(
  File "/tmp/venv/lib/python3.10/site-packages/icontract/_represent.py", line 463, in repr_values
    recompute_visitor.visit(node=lambda_inspection.node.body)
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/tmp/venv/lib/python3.10/site-packages/icontract/_recompute.py", line 577, in visit_Call
    args.append(self.visit(node=arg_node))
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/tmp/venv/lib/python3.10/site-packages/icontract/_recompute.py", line 882, in visit_ListComp
    result = self._execute_comprehension(node=node)
  File "/tmp/venv/lib/python3.10/site-packages/icontract/_recompute.py", line 807, in _execute_comprehension
    code = compile(source=module_node, filename='<ast>', mode='exec')
TypeError: required field "posonlyargs" missing from arguments

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/spam.py", line 11, in <module>
    spam(*[])
  File "/tmp/venv/lib/python3.10/site-packages/icontract/_checkers.py", line 628, in wrapper
    violation_error = _assert_preconditions(
  File "/tmp/venv/lib/python3.10/site-packages/icontract/_checkers.py", line 290, in _assert_preconditions
    exception = _create_violation_error(contract=contract, resolved_kwargs=resolved_kwargs)
  File "/tmp/venv/lib/python3.10/site-packages/icontract/_checkers.py", line 192, in _create_violation_error
    raise RuntimeError(''.join(parts)) from err
RuntimeError: Failed to recompute the values of the contract condition:
File /tmp/spam.py, line 4 in <module>:
lambda _ARGS: bool([s for s in _ARGS])
```

**Comment by mristin** [comment] 2021-11-23 18:48
Thanks a lot, @claudio-ebel! How critical is this bug for you? I could try to have it fixed by Thursday evening CET.

**Comment by claudio-ebel** [comment] 2021-11-24 14:16
Wow, thank YOU a lot! This bug is _not_ critical for me at all! It is only triggered in one of my `pytest` tests. If your fix needs longer (> a few weeks), I will create a little workaround in my code.

**Comment by mristin** [comment] 2021-11-25 11:35
@claudio-ebel could you please check that the issue is fixed with the newest code on the master branch? If so, I'll publish a new minor version to PyPI.

**Closed** 2021-11-25 11:34 UTC

**Comment by mristin** [comment] 2021-11-25 11:37
@claudio-ebel  P.S. If you haven't done so, could you please star the repository on GitHub to give it some visibility?

**Comment by claudio-ebel** [comment] 2021-11-26 13:34
> @claudio-ebel could you please check that the issue is fixed with the newest code on the master branch? If so, I'll publish a new minor version to PyPI.

Yes, your fix solved all the issues for all four combinations:
- python 3.9 the minimal working example
- python 3.9 with the tests in my project
- python 3.10 the minimal working example
- python 3.10 with the tests in my project

Thank you so much! 👏👏👏

> @claudio-ebel P.S. If you haven't done so, could you please star the repository on GitHub to give it some visibility?

Done! ⭐ Your suggestion was very good – I was not aware of that github feature.

**Comment by mristin** [comment] 2021-11-28 19:25
@claudio-ebel the new minor version, 2.6.0, should be now on PyPI. Thanks for the star ;)
